### ISSUE TITLE
aeg-jaxrs and aeg-webui throw exceptions and close

### ISSUE THREAD

**Issue by AegeusCoin** [AegeusCoin/aegeus-ui#54]
In testing the latest comits from https://github.com/AegeusCoin/aegeus-ui/pull/50 - starting up all containers results in aeg-jaxrs and aeg-webui throwing exceptions and ultimately shutting down.

docker logs aeg-jaxrs
IPFS Address: /ip4/172.17.0.3/tcp/5001
IPFS Version: 0.4.18
AegeusBlockchain: http://aeg:*******@172.17.0.2:51473
Error executing command
wf.bitcoin.javabitcoindrpcclient.BitcoinRPCException: RPC Query Failed (method: getnetworkinfo, params: [], response code: 500 responseMessage Internal Server Error, response: {"result":null,"error":{"code":-28,"message":"Loading block index..."},"id":null}

        at wf.bitcoin.javabitcoindrpcclient.BitcoinJSONRPCClient.query(BitcoinJSONRPCClient.java:244)
        at wf.bitcoin.javabitcoindrpcclient.BitcoinJSONRPCClient.getNetworkInfo(BitcoinJSONRPCClient.java:1082)
        at io.nessus.ipfs.jaxrs.JAXRSApplication.serverStart(JAXRSApplication.java:103)
        at io.nessus.ipfs.jaxrs.JAXRSApplication.main(JAXRSApplication.java:85)

docker logs aeg-webui
IPFS Gateway: http://104.156.230.116:8080/ipfs
AegeusBlockchain: http://aeg:*******@172.17.0.2:51473
Exception in thread "main" wf.bitcoin.javabitcoindrpcclient.BitcoinRPCException: RPC Query Failed (method: getnetworkinfo, params: [], response code: 500 responseMessage Internal Server Error, response: {"result":null,"error":{"code":-28,"message":"Loading block index..."},"id":null}

        at wf.bitcoin.javabitcoindrpcclient.BitcoinJSONRPCClient.query(BitcoinJSONRPCClient.java:244)
        at wf.bitcoin.javabitcoindrpcclient.BitcoinJSONRPCClient.getNetworkInfo(BitcoinJSONRPCClient.java:1082)
        at io.nessus.AbstractNetwork.getNetworkInfo(AbstractNetwork.java:55)
        at io.nessus.ipfs.portal.NessusWebUI.start(NessusWebUI.java:72)
        at io.aegeus.ipfs.portal.AegeusWebUI.main(AegeusWebUI.java:18)

**Comment by AegeusCoin** [comment]
It's worth mentioning that after waiting some time, you can start both back up using: docker start aeg-jaxrs aeg-webui.  A check in place for the blockchain and wallet being loaded already would remedy this.

**Comment by tdiesler** [comment]
Yes, blocked by https://github.com/tdiesler/nessus/issues/80
