### ISSUE TITLE
Find address may lead to IndexOutOfBoundsException

### ISSUE THREAD

**Issue by tdiesler** [AegeusCoin/aegeus-ui#61]
```
Nov 29, 2018 6:17:03 AM wf.bitcoin.javabitcoindrpcclient.BitcoinJSONRPCClient$TransactionWrapper raw
WARNING: RPC Query Failed (method: getrawtransaction, params: [8704607ad618134d978b4137d2c06519318f342a832517d0d2989e5a5a8afdc6, 1], response code: 500 responseMessage Internal Server Error, response: {"result":null,"error":{"code":-5,"message":"No information available about transaction"},"id":"1"}

ERROR executing request
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at io.nessus.AbstractWallet.listLockUnspent(AbstractWallet.java:398)
	at io.nessus.core.ipfs.impl.DefaultContentManager.listLockedAndUnlockedUnspent(DefaultContentManager.java:1100)
	at io.nessus.core.ipfs.impl.DefaultContentManager.findAddressRegistation(DefaultContentManager.java:469)
	at io.nessus.ipfs.jaxrs.JAXRSResource.findAddressRegistation(JAXRSResource.java:74)
```

**Comment by tdiesler** [comment]
Adding some more debug logging ...

The wallet reports 

```
root@1e9e7609605c:/# aegeus-cli listlockunspent
[
    {
        "txid" : "853e910bedb7c8213bc93cab7e8337e0a59731db1e0c8968d2e19355d850bdc5",
        "vout" : 1
    }
]
```

Adding this code, I see ...

```
    /**
     * [FIXME #13] listlockunspent may return stale data
     * https://github.com/AegeusCoin/aegeus/issues/13
     */
    @Override
    protected Tx getLockedTransaction(String txId) {
        Tx result = null;
        try {
            LOG.warn("Getting Tx: {}", txId);
            result = super.getTransaction(txId);
            LOG.warn("Got Tx: {}", result);
        } catch (BitcoinRPCException ex) {
            LOG.warn("Cannot get Tx: " + txId, ex);
            if (ex.getMessage().contains("Invalid or non-wallet transaction id")) {
                return null;
            }
            throw ex;
        }
        return result;
    }
```

```
Getting Tx: 853e910bedb7c8213bc93cab7e8337e0a59731db1e0c8968d2e19355d850bdc5
Nov 29, 2018 6:44:36 AM wf.bitcoin.javabitcoindrpcclient.BitcoinJSONRPCClient$TransactionWrapper raw
WARNING: RPC Query Failed (method: getrawtransaction, params: [853e910bedb7c8213bc93cab7e8337e0a59731db1e0c8968d2e19355d850bdc5, 1], response code: 500 responseMessage Internal Server Error, response: {"result":null,"error":{"code":-5,"message":"No information available about transaction"},"id":"1"}

Got Tx: [tx=853e910bedb7c8213bc93cab7e8337e0a59731db1e0c8968d2e19355d850bdc5, vin=0, vout=0]
ERROR executing request
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at io.nessus.AbstractWallet.listLockUnspent(AbstractWallet.java:398)
	at io.nessus.core.ipfs.impl.DefaultContentManager.listLockedAndUnlockedUnspent(DefaultContentManager.java:1100)
	at io.nessus.core.ipfs.impl.DefaultContentManager.findAddressRegistation(DefaultContentManager.java:469)
	at io.nessus.ipfs.jaxrs.JAXRSResource.findAddressRegistation(JAXRSResource.java:74)
```

**Comment by tdiesler** [comment]
Oh dear, even a manual unlock does not fix it

```
root@1e9e7609605c:/# aegeus-cli lockunspent false '[{"txid":"853e910bedb7c8213bc93cab7e8337e0a59731db1e0c8968d2e19355d850bdc5","vout":1}]'
true
root@1e9e7609605c:/# aegeus-cli listlockunspent
[
    {
        "txid" : "853e910bedb7c8213bc93cab7e8337e0a59731db1e0c8968d2e19355d850bdc5",
        "vout" : 1
    }
]
```

**Comment by tdiesler** [comment]
Related to https://github.com/Polve/JavaBitcoindRpcClient/issues/88

**Comment by tdiesler** [comment]
out-of-date
